config/routes.rb
Rails.application.routes.draw do

  get 'feed/index'

  devise_for :users
  
  resources :users
  
  resources :stocks
  
  post 'update_holding' => 'stocks#update_holding'
  
  post 'create_comment' => 'comments#create_comment'
  
  post 'find_create_stock' => 'stocks#find_create_stock'

  get 'welcome/index'
  root to: 'welcome#index'

end

app/controllers/feed_controller.rb
class FeedController < ApplicationController
  def index
    @events = Event.all
    @holdings = Holding.all
  end
  
end

app/helpers/feed_helper.rb
module FeedHelper
  def link_stock(e)
    link_to "#{Stock.find(e.stock_id).symbol}", stock_path(Stock.find(e.stock_id))
  end
  
  def gain_color(e)
    if e.history.pct_gain > 0
      return "green"
    elsif e.history.pct_gain < 0
      return "red"
    end
  end
  
  def link_user(e)
    link_to "#{User.find(e.user_id).name}", user_path(e.user_id)
  end
end

app/views/feed/_events.html.erb
  <% @events.each do |e| %>
    <div class="media">

      <% if User.find(e.user_id).picture? %>
        <div class="media-left media-middle"><%= link_to image_tag( User.find(e.user_id).picture_url(:large), width: 100, height:100, class: 'media-objet img-circle'), user_path(e.user_id) %></div>
      <% end %>
      <div class="media-body">
    <% if e.buy %>
      <% if e.initiate %>
          <div class="media-heading"><h2>Buy @<%= link_stock(e) %>&nbsp<span><h4 class="pull-right"><%= distance_of_time_in_words(e.created_at, Time.now) %> ago</h4></span></h2></div>
          <h3><%= link_user(e) %> initiated a position in @<%= link_stock(e) %> buying <%= e.qty %> shares at $<%= e.price %></h3>
      <% else %>
          <div class="media-heading"><h2>Buy @<%= link_stock(e) %><span><h4 class="pull-right"><%= distance_of_time_in_words(e.created_at, Time.now) %> ago</h4></span></h2></div>
          <h3><%= link_user(e) %> increased holdings of @<%= link_stock(e) %> by <%= e.qty %> at $<%= e.price %></h3>
      <% end %>
    <% else %>
      <% if e.close %>
          <div class="media-heading"><h2>Closed @<%= link_stock(e) %><span><h4 class="pull-right"><%= distance_of_time_in_words(e.created_at, Time.now) %> ago</h4></span></h2></div>
          <h3><%= link_user(e) %> sold <%= e.qty %> shares at $<%= e.price %> and closed position on @<%= link_stock(e) %>, realizing <span style="color:<%= gain_color(e) %>"><%= (e.history.pct_gain).round(2) %></span></h3>
      <% else %>
          <div class="media-heading"><h2>Sell @<%= link_stock(e) %><span><h4 class="pull-right"><%= distance_of_time_in_words(e.created_at, Time.now) %> ago</h4></span></h2></div>
          <h3><%= link_user(e) %> sold <%= e.qty %> shares of @<%= link_stock(e) %> at $<%= e.price %></h3>
      <% end %>
    <% end %>
          <span type="button" class="glyphicon glyphicon-pencil" style="color: #337AB7;" data-toggle="modal" data-target="#commentModal" data-event="<%= e.id %>"><%= e.comments.count %></span>
      </div>
    </div>
      
      <!--Comments-->
      
      <div class="modal fade" id="commentModal" tabindex="-1" role="dialog" aria-labelledby="commentModalLabel">
        <div class="modal-dialog" role="document">
          <div class="modal-content">
            <div class="modal-header">
              <button type="button" class="close" data-dismiss="modal" aria-label="Close"><span aria-hidden="true">&times;</span></button>
              <h4 class="modal-title" id="exampleModalLabel">Comment</h4>
            </div>
            <div class="modal-body">
              <%= form_tag create_comment_path do %>
                <%= hidden_field_tag (:event) %>
                <%= text_area_tag(:content, "", size: "40x6", class: 'center-block') %>
            </div>
            <div class="modal-footer">
                <%= submit_tag "Post", name: nil, class: "btn btn-primary" %>
              <% end %>
            </div>
          </div>
        </div>
      </div>
  <% end %>
  

<script>
$('#commentModal').on('show.bs.modal', function (event) {
  var button = $(event.relatedTarget) // Button that triggered the modal
  var event = button.data('event') // Extract info from data-* attributes
  // If necessary, you could initiate an AJAX request here (and then do the updating in a callback).
  // Update the modal's content. We'll use jQuery here, but you could use a data binding library or other methods instead.
  var modal = $(this)
  modal.find('.modal-body #event').val(event)
})
</script>  

app/views/feed/index.html.erb
<div class="container-fluid">
  <h1>Feed</h1>
  <h3>Make a Trade</h3>
  <%= render "stocks/trade_action" %>
  <%= render "events" %>
</div>