config/routes.rb
Rails.application.routes.draw do

  get 'feed/index'

  devise_for :users
  
  resources :users
  
  resources :stocks
  
  post 'update_holding' => 'stocks#update_holding'
  
  post 'create_comment' => 'comments#create_comment'
  
  post 'find_create_stock' => 'stocks#find_create_stock'

  get 'welcome/index'
  root to: 'welcome#index'

end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>Workspace</title>
  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
  <link href='https://fonts.googleapis.com/css?family=Open+Sans:400,300,700'
 rel='stylesheet' type='text/css'>
  <%= javascript_include_tag "//www.google.com/jsapi", "chartkick" %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
  <%= csrf_meta_tags %>
</head>
<body class="mobile">
<div class="container-fluid" style="background-color:black;">
  <nav class="navbar navbar-default">
    <ul class="nav nav-pills navbar-left" id="full-nav">
      <li role="presentation" class="active"><%= link_to "Bullish", root_path, class: 'navbar-brand' %></li>
      <li role="presentation"><%= link_to "Home", root_path %></li>
      <li role ="presentation"><%= link_to "Feed", feed_index_path %></li>
      <li role="presentation"><%= link_to "Rankings", root_path %></li>
    </ul>
        <%= form_tag(find_create_stock_path, class: 'navbar-form navbar-left') do %>
        <div class="form-group">
          <%= text_field_tag(:search, "", placeholder: 'Lookup Stock', class: 'form-control') %>
        </div>
          <%= submit_tag("Go!", class: 'btn btn-default') %>
        <% end %>
    <ul class="nav nav-pills navbar-right">
      <% if current_user %>
        <li role="presentation"><%= link_to "Hi #{current_user.name || current_user.email}!", user_path(current_user) %></li>
        <li role="presentation"><%= link_to "Sign Out", destroy_user_session_path, method: :delete %> </li>
      <% else %>
        <li role="presentation" class="pull-right"><%= link_to "Login", new_user_session_path %></li>
        <li role="presentation" class="pull-right"><%= link_to "Signup", new_user_registration_path %></li>
      <% end %>
    </ul>
  </div>
  </nav>
  <% if current_user %>
    <nav class="navbar navbar-default navbar-fixed-bottom tabs" id="tab-nav">
      <div class="row">
        <div class="col-md-3 col-xs-3">
          <%= link_to image_tag("feed_tab.png", class: 'center-block'), feed_index_path %>
          <h4 class="text-center">Feed</h4>
        </div>
        <div class="col-md-3 col-xs-3">
          <%= link_to image_tag("rankings_tab.png", class: 'center-block'), root_path %>
          <h4 class="text-center">Rankings</h4>
          </div>
        <div class="col-md-3 col-xs-3">
          <%= link_to image_tag("profile_tab.png", class: 'center-block'), user_path(current_user) %>
          <h4 class="text-center">Profile</h4>
        </div>
        <div class="col-md-3 col-xs-3">
          <%= link_to image_tag("settings_tab.png", class: 'center-block'), edit_user_registration_path %>
          <h4 class="text-center">Settings</h4>
        </div>
      </div>
    </nav>
  <% end %>
</div>

  <% if flash[:notice] %>
  <div class="alert alert-success">
    <button type="button" class=:"close" data-dismiss="alert">&times;</button>
    <%= flash[:notice] %>
  </div>
    <% elsif flash[:error] %>
  <div class="alert alert-danger">
    <button type="button" class=:"close" data-dismiss="alert">&times;</button>
    <%= flash[:error] %>
  </div>
    <% elsif flash[:alert] %>
  <div class="alert alert-warning">
    <button type="button" class=:"close" data-dismiss="alert">&times;</button>
    <%= flash[:alert] %>
  </div>
  <% end %>
  
<%= yield %>

</body>
</html>